name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: mix test
    - name: Build image
      uses: actions/docker/cli@master
      with:
        args: "build -t changi ."
    - name: Tag image
      uses: actions/docker/cli@master
      with:
        args: "tag changi jiayuyi/changi:${{ github.sha }}"
    - name: Login to Docker Hub
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push image to Docker Hub
      uses: actions/docker/cli@master
      with:
        args: "push jiayuyi/changi:${{ github.sha }}"
